schema: graphql/schema.graphql
documents: ['graphql/**/*.graphql', 'client/**/*.{ts,tsx}', 'server/**/*.{ts,tsx}']
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        config:
          dedupeFragments: true
          # Reduces bundle size
          enumsAsTypes: true
          gqlTagName: gql # Specify custom gql tag name
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
